#!/bin/bash
set -euo pipefail

rm -rf build
mkdir build

cd ./src
zip -r ../build/z-permalink-1.0.1.xpi *
cd ../build

jq ".addons[\"z-permalink@zotero.org\"].updates[0].update_hash = \"sha256:`shasum -a 256 z-permalink-1.0.1.xpi | cut -d' ' -f1`\"" ../updates.json.tmpl > updates-1.0.1.json
